#' Calculate Portfolio Duration and Convexity
#'
#' Calculates Macaulay duration, modified duration, and optionally analytical
#' convexity for a loan portfolio based on projected cash flows from
#' \code{calculate_cash_flows()}.
#'
#' @param loan_cash_flows Data frame. Output from \code{calculate_cash_flows()}
#'   containing projected loan cash flows with required columns: LOAN_ID,
#'   rate, eff_date, date, month, total_payment, investor_total.
#' @param discount_rate Numeric or NULL. Annual discount rate for present value
#'   calculations (e.g., 0.06 for 6% per year). If NULL (default), uses each
#'   loan's rate from the loan_cash_flows data. If a scalar, applies that rate
#'   uniformly across all loans. When discount_rate is NULL, present values are
#'   computed using loan-level rates. Sensitivity adjustments use each cash
#'   flow's discount rate before aggregation, rather than an average rate.
#'   Supplied discount rates and the rate column must be finite and non-negative.
#' @param cash_flow_column Character. Column name for cash flows to discount.
#'   Options:
#'   \itemize{
#'     \item "total_payment" (default): Gross cash flow generated by the loan
#'       (gross_interest + total_principal), before any fee deductions or
#'       investor allocations
#'     \item "investor_total": Net cash flow to the investor after applying
#'       servicing fees, reporting fees, origination fees, credit losses
#'       (if applicable), and investor_share percentage
#'   }
#' @param include_convexity Logical. If TRUE, calculates and includes analytical
#'   convexity in the output. Default is FALSE. Note: Analytical convexity
#'   assumes cash flows are held constant; convexity reflects discounting effects
#'   only and does not incorporate rate-dependent prepayment behavior. It answers
#'   "What convexity would this portfolio have if borrowers didn't change
#'   prepayment behavior?"
#'
#' @param validate_month_index Logical. If TRUE (default), errors when the month
#'   column for any individual loan does not begin at 1 or is not contiguous.
#'   Set FALSE to analyse a deliberately offset or filtered projection window.
#'   Duplicate loan-month records and invalid data are always rejected.
#'
#' @return A single-row data frame with portfolio-level metrics:
#'   \itemize{
#'     \item portfolio_pv: Total present value of all cash flows
#'     \item macaulay_duration: Time-weighted average maturity in years
#'     \item modified_duration: Interest rate sensitivity measure in years
#'     \item analytical_convexity: (only if include_convexity = TRUE)
#'       Fixed cash flow convexity measure
#'   }
#'
#' @details
#' Input must be non-empty and use one common eff_date across the portfolio.
#' IDs and dates must be valid and non-missing; the selected cash-flow amounts
#' must be finite, non-negative numbers. Missing rows are never silently removed.
#' Month indices must be finite positive integers, unique within each loan;
#' loans may have different final months and input rows may be unordered.
#' Zero-weight loans continue to be excluded with a warning.
#' Timing is determined by month / 12, not by actual calendar day counts.
#' The sequence check cannot detect a missing final payment without contractual
#' maturity information; an incomplete projection can still produce a metric.
#'
#' All calculations use monthly compounding. Present values are computed as:
#' PV_t = CF_t / (1 + y/12)^t, where y is the annual discount rate and t is
#' time in months from eff_date. The month column is the projection index: month = 1
#' is the first projected cash flow, falling one month after eff_date,
#' so t = month months and t_years = month / 12.
#'
#' Duration measures the weighted average time until cash flows are received,
#' expressed in years. Modified duration approximates the percentage change in
#' present value for a 1% change in interest rates, assuming monthly compounding.
#'
#' The function calculates:
#' \itemize{
#'   \item Macaulay Duration = Σ(t × PV_t) / Σ(PV_t), where t is time in years
#'   \item Modified Duration = Σ(PV_t × t / (1 + y_t/12)) / Σ(PV_t)
#'   \item Analytical Convexity = Σ(PV_t × t × (t + 1/12) / (1 + y_t/12)^2) / Σ(PV_t),
#'     where t is in years and y_t is the annual discount rate for that cash flow
#' }
#'
#' These sensitivities describe a parallel shift of all discount rates with
#' cash flows held fixed. For a common rate y, modified duration reduces to
#' Macaulay duration / (1 + y/12). This is not effective duration: rate-dependent
#' prepayments are not recomputed.
#'
#' @examples
#' \dontrun{
#' # Calculate duration using each loan's current rate
#' duration_results <- calculate_duration(loan_cash_flows)
#'
#' # Calculate duration using a market rate of 5%
#' duration_results <- calculate_duration(loan_cash_flows, discount_rate = 0.05)
#'
#' # Calculate duration for investor's economic interest with convexity
#' duration_results <- calculate_duration(
#'   loan_cash_flows,
#'   cash_flow_column = "investor_total",
#'   include_convexity = TRUE
#' )
#' }
#'
#' @importFrom stats weighted.mean
#' @export
calculate_duration <- function(loan_cash_flows,
                               discount_rate = NULL,
                               cash_flow_column = "total_payment",
                               include_convexity = FALSE,
                               validate_month_index = TRUE
                               ) {

  if (!is.character(cash_flow_column) || length(cash_flow_column) != 1L ||
      is.na(cash_flow_column) || !cash_flow_column %in% c("total_payment", "investor_total")) {
    stop("cash_flow_column must be either 'total_payment' or 'investor_total'")
  }
  if (!is.null(discount_rate)) {
    if (!is.numeric(discount_rate) || length(discount_rate) != 1L ||
        !is.null(dim(discount_rate)) || !is.finite(discount_rate)) {
      stop("discount_rate must be NULL or a single numeric value that is finite")
    }
    if (discount_rate < 0) stop("discount_rate must be non-negative")
  }
  validate_analytics_flag(include_convexity, "include_convexity")
  duration_data <- validate_analytics_data(
    loan_cash_flows, cash_flow_column,
    c("LOAN_ID", "rate", "eff_date", "date", "month", "total_payment", "investor_total"),
    validate_month_index, check_rate = TRUE
  )

  # Determine discount rate to use for each loan
  if (is.null(discount_rate)) {
    # Use each loan's rate
    duration_data <- duration_data %>%
      mutate(discount_rate_used = rate)
  } else {
    # Use user-specified scalar rate
    duration_data <- duration_data %>%
      mutate(discount_rate_used = discount_rate)
  }

  # Calculate time periods using month column and present values with monthly compounding ----
  duration_data <- duration_data %>%
    mutate(
      t_months = month,
      t_years = t_months / 12,

      # Present value calculation using monthly compounding
      pv = .data[[cash_flow_column]] / (1 + discount_rate_used / 12)^t_months,
      pv_weighted_time = t_years * pv
    )

  # Add convexity term if requested
  if (include_convexity) {
    duration_data <- duration_data %>%
      mutate(
        # Convexity formula: PV * t * (t + 1/12) for monthly cash flows, expressed in years
        convexity_term = pv * t_years * (t_years + 1/12) / (1 + discount_rate_used / 12)^2
      )
  }

  # Aggregate at loan level ----
  loan_level <- duration_data %>%
    group_by(LOAN_ID) %>%
    summarise(
      loan_pv = sum(pv),
      loan_duration = sum(pv_weighted_time) / loan_pv,
      loan_convexity = if (include_convexity) {
        sum(convexity_term) / loan_pv
      } else {
        NA_real_
      },
      loan_modified_duration = sum(pv_weighted_time / (1 + discount_rate_used / 12)) / loan_pv,
      .groups = "drop"
    )

  # Filter out loans with zero PV and warn if any removed ----
  zero_pv_loans <- loan_level %>% filter(loan_pv == 0)
  if (nrow(zero_pv_loans) > 0) {
    warning("Removed ", nrow(zero_pv_loans),
            " loan(s) with zero present value from duration calculation")
  }
  loan_level <- loan_level %>% filter(loan_pv > 0)

  # Check for remaining loans
  if (nrow(loan_level) == 0) {
    stop("No loans remaining after filtering zero PV. Check cash flows and discount rates.")
  }

  # Calculate portfolio-level metrics ----
  portfolio_pv <- sum(loan_level$loan_pv)

  if (portfolio_pv == 0) {
    stop("Portfolio present value is zero. Check cash flows and discount rates.")
  }

  macaulay_duration <- weighted.mean(loan_level$loan_duration,
                                     loan_level$loan_pv)

  # Sensitivities to a parallel shift of the discount rates, holding cash flows
  # fixed. Apply each discount-rate denominator before portfolio aggregation.
  modified_duration <- weighted.mean(loan_level$loan_modified_duration, loan_level$loan_pv)

  # Build output ----
  result <- data.frame(
    portfolio_pv = portfolio_pv,
    macaulay_duration = macaulay_duration,
    modified_duration = modified_duration
  )

  # Add convexity if requested
  if (include_convexity) {
    # Portfolio convexity calculation with monthly compounding
    portfolio_convexity <- sum(loan_level$loan_convexity * loan_level$loan_pv) /
      portfolio_pv

    result$analytical_convexity <- portfolio_convexity
  }

  if (any(!is.finite(as.matrix(result)))) {
    stop("Analytics produced non-finite results; check input magnitudes and discount rates.")
  }
  return(result)
}
