#' Calculate Portfolio Duration and Convexity
#'
#' Calculates Macaulay duration, modified duration, and optionally analytical
#' convexity for a loan portfolio based on projected cash flows from
#' \code{calculate_cash_flows()}.
#'
#' @param loan_cash_flows Data frame. Output from \code{calculate_cash_flows()}
#'   containing projected loan cash flows with required columns: LOAN_ID,
#'   rate, eff_date, date, month, total_payment, investor_total.
#' @param discount_rate Numeric or NULL. Annual discount rate for present value
#'   calculations (e.g., 0.06 for 6% per year). If NULL (default), uses each
#'   loan's rate from the loan_cash_flows data. If a scalar, applies that rate
#'   uniformly across all loans. When discount_rate is NULL, present values are
#'   computed using loan-level rates, and the portfolio discount rate used in
#'   the modified duration adjustment is the PV-weighted average loan rate.
#' @param cash_flow_column Character. Column name for cash flows to discount.
#'   Options:
#'   \itemize{
#'     \item "total_payment" (default): Gross cash flow generated by the loan
#'       (gross_interest + total_principal), before any fee deductions or
#'       investor allocations
#'     \item "investor_total": Net cash flow to the investor after applying
#'       servicing fees, reporting fees, origination fees, credit losses
#'       (if applicable), and investor_share percentage
#'   }
#' @param include_convexity Logical. If TRUE, calculates and includes analytical
#'   convexity in the output. Default is FALSE. Note: Analytical convexity
#'   assumes cash flows are held constant; convexity reflects discounting effects
#'   only and does not incorporate rate-dependent prepayment behavior. It answers
#'   "What convexity would this portfolio have if borrowers didn't change
#'   prepayment behavior?"
#'
#' @return A single-row data frame with portfolio-level metrics:
#'   \itemize{
#'     \item portfolio_pv: Total present value of all cash flows
#'     \item macaulay_duration: Time-weighted average maturity in years
#'     \item modified_duration: Interest rate sensitivity measure in years
#'     \item analytical_convexity: (only if include_convexity = TRUE)
#'       Fixed cash flow convexity measure
#'   }
#'
#' @details
#' All calculations use monthly compounding. Present values are computed as:
#' PV_t = CF_t / (1 + y/12)^t, where y is the annual discount rate and t is
#' time in months from eff_date. The month column is treated as the projection
#' index, where month = 1 corresponds to time 0 (the effective date). Timing
#' calculations use t = (month - 1) / 12 for conversion to years.
#'
#' Duration measures the weighted average time until cash flows are received,
#' expressed in years. Modified duration approximates the percentage change in
#' present value for a 1% change in interest rates, assuming monthly compounding.
#'
#' The function calculates:
#' \itemize{
#'   \item Macaulay Duration = Σ(t × PV_t) / Σ(PV_t), where t is time in years
#'   \item Modified Duration = Macaulay Duration / (1 + y/12), where y is the
#'     discount rate and 12 represents monthly compounding
#'   \item Analytical Convexity = Σ(PV_t × t × (t + 1/12)) / (PV × (1 + y/12)^2),
#'     where t is in years and the formula reflects monthly compounding
#' }
#'
#' When discount_rate is NULL, the function uses a weighted average of loan rates
#' for the modified duration calculation.
#'
#' @examples
#' \dontrun{
#' # Calculate duration using each loan's current rate
#' duration_results <- calculate_duration(loan_cash_flows)
#'
#' # Calculate duration using a market rate of 5%
#' duration_results <- calculate_duration(loan_cash_flows, discount_rate = 0.05)
#'
#' # Calculate duration for investor's economic interest with convexity
#' duration_results <- calculate_duration(
#'   loan_cash_flows,
#'   cash_flow_column = "investor_total",
#'   include_convexity = TRUE
#' )
#' }
#'
#' @importFrom stats weighted.mean
#' @export
calculate_duration <- function(loan_cash_flows,
                               discount_rate = NULL,
                               cash_flow_column = "total_payment",
                               include_convexity = FALSE) {

  # Input validation ----
  if (!is.data.frame(loan_cash_flows)) {
    stop("loan_cash_flows must be a data frame")
  }

  required_cols <- c("LOAN_ID", "rate", "eff_date",
                     "date", "month", "total_payment", "investor_total")
  missing_cols <- setdiff(required_cols, names(loan_cash_flows))
  if (length(missing_cols) > 0) {
    stop("loan_cash_flows is missing required columns: ",
         paste(missing_cols, collapse = ", "))
  }

  if (!cash_flow_column %in% c("total_payment", "investor_total")) {
    stop("cash_flow_column must be either 'total_payment' or 'investor_total'")
  }

  if (!is.null(discount_rate)) {
    if (!is.numeric(discount_rate) || length(discount_rate) != 1) {
      stop("discount_rate must be NULL or a single numeric value")
    }
    if (discount_rate < 0) {
      stop("discount_rate must be non-negative")
    }
  }

  if (!is.logical(include_convexity) || length(include_convexity) != 1) {
    stop("include_convexity must be TRUE or FALSE")
  }

  # Ensure required columns are not all NA
  if (all(is.na(loan_cash_flows$LOAN_ID))) {
    stop("LOAN_ID column contains only NA values")
  }

  if (all(is.na(loan_cash_flows[[cash_flow_column]]))) {
    stop(cash_flow_column, " column contains only NA values")
  }

  # Data preparation ----
  # Remove rows with missing critical data
  duration_data <- loan_cash_flows %>%
    filter(!is.na(LOAN_ID),
           !is.na(rate),
           !is.na(eff_date),
           !is.na(date),
           !is.na(month),
           !is.na(.data[[cash_flow_column]])) %>%
    mutate(
      eff_date = as.Date(eff_date),
      date = as.Date(date)
    )

  if (nrow(duration_data) == 0) {
    stop("No valid rows remaining after removing missing values in required columns")
  }

  # Validate date conversion succeeded ----
  if (any(is.na(duration_data$eff_date)) || any(is.na(duration_data$date))) {
    stop("Some date values could not be converted to Date format. Check eff_date and date columns.")
  }

  # Validate month column ----
  if (any(duration_data$month < 1, na.rm = TRUE)) {
    stop("month column contains values less than 1. Month must be >= 1 (month = 1 corresponds to time 0)")
  }

  if (any(duration_data$month != floor(duration_data$month), na.rm = TRUE)) {
    stop("month column contains non-integer values. Month must be an integer >= 1")
  }

  # Determine discount rate to use for each loan
  if (is.null(discount_rate)) {
    # Use each loan's rate
    duration_data <- duration_data %>%
      mutate(discount_rate_used = rate)
  } else {
    # Use user-specified scalar rate
    duration_data <- duration_data %>%
      mutate(discount_rate_used = discount_rate)
  }

  # Calculate time periods using month column and present values with monthly compounding ----
  duration_data <- duration_data %>%
    mutate(
      t_months = month - 1,
      t_years = t_months / 12,

      # Present value calculation using monthly compounding
      pv = .data[[cash_flow_column]] / (1 + discount_rate_used / 12)^t_months,
      pv_weighted_time = t_years * pv
    )

  # Add convexity term if requested
  if (include_convexity) {
    duration_data <- duration_data %>%
      mutate(
        # Convexity formula: PV * t * (t + 1/12) for monthly cash flows, expressed in years
        convexity_term = pv * t_years * (t_years + 1/12)
      )
  }

  # Aggregate at loan level ----
  loan_level <- duration_data %>%
    group_by(LOAN_ID) %>%
    summarise(
      loan_pv = sum(pv, na.rm = TRUE),
      loan_duration = sum(pv_weighted_time, na.rm = TRUE) / loan_pv,
      loan_convexity = if (include_convexity) {
        sum(convexity_term, na.rm = TRUE) / loan_pv
      } else {
        NA_real_
      },
      avg_discount_rate = mean(discount_rate_used, na.rm = TRUE),
      .groups = "drop"
    )

  # Filter out loans with zero PV and warn if any removed ----
  zero_pv_loans <- loan_level %>% filter(loan_pv == 0)
  if (nrow(zero_pv_loans) > 0) {
    warning("Removed ", nrow(zero_pv_loans),
            " loan(s) with zero present value from duration calculation")
  }
  loan_level <- loan_level %>% filter(loan_pv > 0)

  # Check for remaining loans
  if (nrow(loan_level) == 0) {
    stop("No loans remaining after filtering zero PV. Check cash flows and discount rates.")
  }

  # Calculate portfolio-level metrics ----
  portfolio_pv <- sum(loan_level$loan_pv, na.rm = TRUE)

  if (portfolio_pv == 0) {
    stop("Portfolio present value is zero. Check cash flows and discount rates.")
  }

  macaulay_duration <- weighted.mean(loan_level$loan_duration,
                                     loan_level$loan_pv,
                                     na.rm = TRUE)

  # For modified duration, determine the discount rate to use
  if (is.null(discount_rate)) {
    # Use weighted average of loan rates
    portfolio_discount_rate <- weighted.mean(loan_level$avg_discount_rate,
                                             loan_level$loan_pv,
                                             na.rm = TRUE)
  } else {
    # Use the scalar rate provided
    portfolio_discount_rate <- discount_rate
  }

  # Modified duration = Macaulay / (1 + y/12) where y is annual rate, 12 for monthly compounding
  modified_duration <- macaulay_duration / (1 + portfolio_discount_rate / 12)

  # Build output ----
  result <- data.frame(
    portfolio_pv = portfolio_pv,
    macaulay_duration = macaulay_duration,
    modified_duration = modified_duration
  )

  # Add convexity if requested
  if (include_convexity) {
    # Portfolio convexity calculation with monthly compounding
    portfolio_convexity <- sum(loan_level$loan_convexity * loan_level$loan_pv,
                               na.rm = TRUE) /
      (portfolio_pv * (1 + portfolio_discount_rate / 12)^2)

    result$analytical_convexity <- portfolio_convexity
  }

  return(result)
}
